### ISSUE TITLE
what are the standard papers discussing methodologies for sbse?

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#11]
here are two. how many others?

- A. Arcuri and L. Briand, "A practical guide for using statistical tests to assess randomized algorithms in software engineering," 2011 33rd International Conference on Software Engineering (ICSE), Honolulu, HI, 2011, pp. 1-10.
doi: 10.1145/1985793.1985795
- Shuai Wang, Shaukat Ali, Tao Yue, Yan Li, and Marius Liaaen. A practical
guide to select quality indicators for assessing pareto-based search algorithms
in search-based software engineering. In International Conference on
Software Engineering, 2016.
- what else?

**Comment by timm** [comment]
mother told me never to argue about stats. maybe we should focus on what we do agree on (evolutionary methods)

pause

oh what the hell

scott-knott is not parametric. it is a clustering method and the operators used to assess the merits of combining clusters are a domain decision

now, usually, it is used with an ANOVA  operator but that is a design choice.  i use non-parametric boostrapping and cliffs delta for the top-down version

for a bottom's up version, as near as i can tell, the canada people use cliffs delta (again, non-parametric) to see if cluster i,j can be replaced by k. if yes, then  repeat for k,l. else, try again with j,k. 

as to kinky friedmann (http://www.kinkyfriedman.com/, just kidding), those plots show so much overlap that i dont know what is going on. and those rank values hide the true eval numbers... never a good thing in my book

as to ease of reading, i dig the plot shown above. or one of wei's charts:

![image](https://user-images.githubusercontent.com/29195/35190734-8ae14f08-fe36-11e7-8130-78c08f8a88a1.png)

**Comment by markuswagnergithub** [comment]
Slightly newer than the Arcuri 2011 is the Arcuri 2013 ("only" 170 citations instead of 430), which is the official extended journal version of the ICSE paper (see footnote on first page)
http://orbilu.uni.lu/handle/10993/1071
