### ISSUE TITLE
snapshot of README.md to TABLE 1

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/ResourcesDataDrivenSBSE#12]

**Comment by timm** [comment]
done! its beautiful

![image](https://user-images.githubusercontent.com/29195/35190700-70fa8a2e-fe35-11e7-8c58-e67a72c53aaf.png)

**Comment by timm** [comment]
done. its beautiful

![page1](https://user-images.githubusercontent.com/29195/35190713-a765560c-fe35-11e7-88a1-5e5b851144b0.png)
