### ISSUE TITLE
have i got the citation right?

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#14]
who contributed  to this project?

https://github.com/ai-se/ResourcesDataDrivenSBSE/blob/master/CITATION.md

**Comment by vivekaxl** [comment]
Updated CITATION.md

**Comment by timm** [comment]
i'd list us all alphabetically (after nair, of course). see below.

but what do other people thing?

________________

1. Vivek Nair
3. Jianfeng Chen
2. Wei Fu
3. George Mathew
4. Tim Menzies
5. Leandro Minku
6. Markus Wagner
7. Zhe Yu,

**Comment by timm** [comment]
https://github.com/ai-se/ResourcesDataDrivenSBSE/blob/master/CITATION.md not updated
