### ISSUE TITLE
highwater marks in SBSE MSR

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#18]
i've got in

- sarro's ICSE15 effort estimation stuff
- all our param tuning stuff
- active elarning (vivek's stuff)

but what about the result of you. what do you think are the high water marks in combining data miners with search?

**Comment by minkull** [comment]
In addition to those and what is already in the paper,
- Linares-Vásquez's FSE'15 Power consumption optimisation (using energy models as surrogates)
- Sarro's ICSE'16 -- tim, I think you might have been referring to icse16 and not 15?
- Hyperheuristics (e.g., some of my stuff PPSN'16 and InfoSciences'18 on SPSP)

**Comment by timm** [comment]
@vivekaxl : are these in the paper?
