### ISSUE TITLE
need a better name

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#19]
data-driven SBSE is really clumsy

**Comment by vivekaxl** [comment]
mSBSE - mutant SBSE

**Comment by vivekaxl** [comment]
X-SBSE - from X-men

**Comment by vivekaxl** [comment]
DSE - Data Driven (Sb) SE

**Comment by markuswagnergithub** [comment]
The Singularity

**Comment by timm** [comment]
databased

or is that term taken?

**Comment by vivekaxl** [comment]
We stick to DSE (as mentioned in the MSR abstract submission).
