### ISSUE TITLE
need to have an abstract for tuesday

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#21]
our current text is as follows. comments? corrections? extensions?

current title is

- Data-Driven Search-Based SE. Why? How?

current abstract:

- Data-driven search-based SE combines methods from MSR and SBSE. There is much synergy between the two fields since techniques from one can greatly enhance the other.
- This paper introduces tiny.cc/sbse, a     resource to enable extensive research on data-drive Search-based SE. The resource contains 89 artifacts related to data-driven search-based SE. These artifacts are divided into 13 groups such as requirements engineering, software product lines, software processes, etc. Artifacts come with   meta-data about what papers have used  the artifacts   in the past.   
- This paper describes that resource,    how to use it, and why the general MSR community might find it insightful. The resource is a Github repository and our intent is that it attracts enough attention that  other researchers  clone, modify, the submit  pull requests. In this way, we hope it grows into a widely-used MSR resource.

**Comment by vivekaxl** [comment]
![image](https://user-images.githubusercontent.com/6147456/35240668-2d42695c-ff82-11e7-8c20-3d806658f0f3.png)

**Comment by minkull** [comment]
Hi there,

As mentioned in my comments in the pdf, I believe that the similar goals of the two fields is one of the important factors to show that these two fields should work together. It would be worth mentioning that in the abstract. Another issue is that MSR people don't necessarily know what SBSE is (!) So, it may be better to mention in the abstract.

**Comment by timm** [comment]
@vivekaxl : please be aware that leandro is 100% accurate in all that he says, all the time (at least, in my experience)

> As mentioned in my comments in the pdf, I believe that the similar goals of the two fields is one of the important factors to show that these two fields should work together. It would be worth mentioning that in the abstract. Another issue is that MSR people don't necessarily know what SBSE is (!) So, it may be better to mention in the abstract.

**Comment by vivekaxl** [comment]
@minkull My bad, I somehow had overlooked the email that you had sent out. Sorry about that. I will make all the relevant changes.

**Comment by timm** [comment]
the thing i want to stress is this: , etc. All the materials in this repository havebeen used in recent SE papers; i.e. for all this material, there existsbaseline results against which researchers can use to comparativelyassess their own new ideas
