### ISSUE TITLE
vivek: what is lost if we dump the current section 4+5?

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#22]
if there is cool stuff there, move it forward.

(but do you see the two bold ital quotes on p2? i'd like to keep them on p2 ins we can)

otherwise, and excuse my hubris, i prefer my new p1,2,3

**Comment by vivekaxl** [comment]
I absolutely love the p1, 2, 3 and it is much better than my draft. 

However, I think that it explains things so fast that a new guy (SBSE or MSR) would have a hard time understand what is going on. I think there is a need for a tutorial session or rather a slow introduction to the concepts. Some parts of current 5 and 6 can be used.

**Comment by vivekaxl** [comment]
Another comment: 
I felt that this paper was written to fit the 'data showcase' style rather than a research vision statement. Is that the intention?

**Comment by timm** [comment]
- data showcase is 6 pages. we need to be a full paper
- agreed. section2 ("what") needs a super brief description of multi-objective, pareto front, domination (which can lead to a superbrief description of hypervolume, spread, igd, gd)
- all done before p3.
- and table 2 can move to p3. 
- over to you

**Comment by vivekaxl** [comment]
I have summarized the content of Section 4 and 5 into a table Figure 2. Please review. @timm
