### ISSUE TITLE
Title of the paper?

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/ResourcesDataDrivenSBSE#23]
Current title: Data-Driven Search-Based SE. Why? How?

**Comment by vivekaxl** [comment]
Data-Driven Search-Based SE. Why? What? How?

**Comment by vivekaxl** [comment]
Introducing Data-Driven Search-Based SE

**Comment by vivekaxl** [comment]
Data-Driven Search-Based Software Engineering---inspired by Harman et al. "Search-Based Software Engineering".

**Comment by vivekaxl** [comment]
Can Software Analytics and Search-based SE converge?

**Comment by vivekaxl** [comment]
Attention: Software Analytics and Search-based SE, please assemble.

**Comment by bigfatnoob** [comment]
Data-Driven Search-based Software Analytics

**Comment by markuswagnergithub** [comment]
Why not go up one level and make it "Data-Driven Software Engineering"?

**Comment by markuswagnergithub** [comment]
Wait. What??? I had not plans of unassigning :p

**Comment by minkull** [comment]
I like "Data-Driven Search-Based Software Engineering", or perhaps "Search-Based Data-Driven Software Engineering" is better. I think that this kind of title could really inspire a whole new area, pretty much like Mark's paper on "Search-Based Software Engineering".
