### ISSUE TITLE
optimising optimisers

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/ResourcesDataDrivenSBSE#26]
Can please you give 2-3 paragraphs on this? It would be very helpful.

Regards, 
Vivek Nair

**Comment by markuswagnergithub** [comment]
Sure, will do. Thanks for poking me. I'll get to it now.

**Comment by vivekaxl** [comment]
Thank you.

**Comment by markuswagnergithub** [comment]
Please check. If it is too long, then the last three sentences can be dropped (starting with "Lastly, ...").
Whatever comes to mind, let me know.
