### ISSUE TITLE
we are getting close to a release candidate

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#27]
now we can critique the overall flow of the document. 

everyone: please critique!

**Comment by timm** [comment]
Fig1 is just frigging amazing. regular fucking work of fucking art. Go team! 

currently our figures have a gray!20 background. Seems too dark.  maybe switch all to gray!10?

**Comment by timm** [comment]
not sure about long lists (like in figure 5). kill those and make them text?

**Comment by timm** [comment]
not 100% convinced fastread fits our definition of ddSbse. if we run out of space, that might be one to go!

**Comment by vivekaxl** [comment]
Regarding section 5, 6 --- I followed the style used by Acuri in his [paper](http://ieeexplore.ieee.org/document/6032439/). 
But, yes, we can get rid of the bullet points and use \noindent\textbf{X} instead.

**Comment by vivekaxl** [comment]
After addressing #28 and #26, we might have around half a page more to work with.

**Comment by vivekaxl** [comment]
> currently our figures have a gray!20 background. Seems too dark. maybe switch all to gray!10?
Done

**Comment by minkull** [comment]
Is the latest version the one in ShareLatex?

**Comment by vivekaxl** [comment]
> Is the latest version the one in ShareLatex?

Yes.

**Comment by minkull** [comment]
Hi, I went through the paper adding some comments and making some alterations. Comments are in red using the TODO command. Some alterations (but not the tiny ones like fixing typos) are in blue, using the llm command. The alterations in the tutorial part are fixing some inaccuracies. If you don't agree with any of the alterations, give a shout!

PS: It's possible to just eliminate the colour blue from the command llm later on, if we don't want to remove every single one of the llm commands from there.
