### ISSUE TITLE
what is the schedule for checking the google forms and updating the site as appropriate?

### ISSUE THREAD

**Issue by timm** [ai-se/ResourcesDataDrivenSBSE#50]
please advise

alos, who is doing the updates? vivek? rahul?

**Comment by rahlk** [comment]
@vivekaxl You want to handle this?

**Comment by rahlk** [comment]
You can use something like this: https://github.com/ai-se/ResourcesDataDrivenSBSE/blob/master/data/render_data.py

You'll probably have to do a git pull -> python script -> git push every time a new entry is made

**Comment by vivekaxl** [comment]
I can take care of it, every other week.
